bareduprj/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("core.urls")),
    path("user/", include("userauths.urls")),
]

if settings.DEBUG:
    urlpatterns +=  static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import index, shop, product_detail_view, blog, blog1, blog2, blog3, blog4, about, contact,add_to_cart, delete_item_from_cart, cart

app_name = "core"

urlpatterns = [
    path("", index, name="index"),
    path("product/<pid>/", product_detail_view, name="product-detail"),
    
    path("shop/", shop, name="shop"),
    path("blog/", blog, name="blog"),
    path("blog1/", blog1, name="blog1"),
    path("blog2/", blog2, name="blog2"),
    path("blog3/", blog3, name="blog3"),
    path("blog4/", blog4, name="blog4"),
    path("about/", about, name="about"),
    path("contact/", contact, name="contact"),
    path("cart/", cart, name="cart"),
    path("add-to-cart/", add_to_cart, name="add-to-cart"),
    path('delete-from-cart/', delete_item_from_cart, name='delete_from_cart'),
]

userauths/urls.py
from django.urls import path 
from userauths import views

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.register_view, name="sign-up"),
    path("sign-in/", views.login_view, name="sign-in"),
    path("sign-out/", views.logout_view, name="sign-out")

]

userauths/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    number = models.CharField(max_length=15)

    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ['username']
    
    
    def __str__(self): 
        return self.username 
    

userauths/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from userauths.models import User

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={"placeholder": "Username", "class": "form-control", "size": "40"}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={"placeholder": "Email", "class": "form-control", "size": "40"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Password", "class": "form-control", "size": "40"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password", "class": "form-control", "size": "40"}))
    
    class Meta:
        model = User
        fields = ['username', 'email']

userauths/views.py
from django.shortcuts import render, redirect
from userauths.forms import UserRegisterForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.contrib.auth import logout

User = settings.AUTH_USER_MODEL
User = get_user_model()

def register_view(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST or None)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hey {username}, Your account was created successfully")
            new_user = authenticate(username=form.cleaned_data['email'],
                                    password=form.cleaned_data['password1'])
            login(request, new_user)
            return redirect('core:index')
    else:
        form = UserRegisterForm()
    
    context = {
        'form': form,
    }
    return render(request, "userauths/sign-up.html", context)

# gets the login credentials and logs the user in
def login_view(request):
    if request.user.is_authenticated:
        messages.warning(request, f"Hey, you are already logged in")
        return redirect("core:index")

    if request.method == "POST":
        email = request.POST.get("email")
        password = request.POST.get("password")
        
        try:
            # Use the correct User model to get the user
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            messages.warning(request, f"User with {email} does not exist")
            return render(request, "userauths/sign-in.html")  # Return to the sign-in page
        
        user = authenticate(request, username=email, password=password)
        
        if user is not None:
            login(request, user)
            messages.success(request, "You Are Logged In.")
            return redirect("core:index")
        else:
            messages.warning(request, "Incorrect password. Please try again.")
            
    return render(request, "userauths/sign-in.html")



def logout_view(request):
    logout(request)
    messages.success(request, "You have logged out")
    return redirect("userauths:sign-in")

templates/userauths/sign-in.html
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Login</title>
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@200;300;400;500;600;700&display=swap");
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: "Open Sans", sans-serif;
        }
        body {
            display: flex;
            align-items: center;
            justify-content: center;
            min-height: 100vh;
            width: 100%;
            padding: 0 10px;
            color: #fff;
        }
        body::before {
            content: "";
            position: absolute;
            width: 100%;
            height: 100%;
            background-image: url('{% static "assets/images/background1.jpeg" %}');
            background-position: center;
            background-size: cover;
        }
        .wrapper {
            width: 600px;
            border-radius: 8px;
            padding: 50px;
            text-align: center;
            border: 1px solid rgba(255, 255, 255, 0.5);
            backdrop-filter: blur(8px);
            -webkit-backdrop-filter: blur(8px);
        }
        .wrapper .title {
            font-size: 20px;
            font-weight: 600;
            text-align: center;
            line-height: 60px;
            color: brown;
            user-select: none;
            border-radius: 15px 15px 0 0;
        }
        form {
            display: flex;
            flex-direction: column;
        }
        .form-group {
            margin-bottom: 20px;
        }
        .form-control {
            width: 100%;
            padding: 15px;
            font-size: 24px;
            border: 1px solid #ccc;
            border-radius: 4px;
            outline: none;
            height: 70px;
        }
        .form-control:focus {
            border-color: #007bff;
        }
        h2 {
            font-size: 2rem;
            margin-bottom: 20px;
            color: #fff;
        }
        button {
            background: #fff;
            color: #000;
            font-weight: 600;
            border: none;
            padding: 12px 20px;
            cursor: pointer;
            border-radius: 3px;
            font-size: 16px;
            border: 2px solid transparent;
            transition: 0.3s ease;
        }
        button:hover {
            color: #fff;
            border-color: #fff;
            background: rgba(255, 255, 255, 0.15);
        }
        .register {
            text-align: center;
            margin-top: 30px;
            color: #fff;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        {% if form.errors %}
            <div class="alert alert-danger">
                <strong>{{ form.errors }}</strong>
            </div>
        {% endif %}
        <div class="title">
            Login
            <p>Don't have an account? <a href="{% url 'userauths:sign-up' %}">Create an account</a></p>
        </div>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <input type="text" required name="email" placeholder="Username or Email" style="width: 100%; padding: 15px; font-size: 19px; border: 1px solid #ccc; border-radius: 4px; outline: none; height: 70px;">
            </div>
            <div class="form-group">
                <input required type="password" name="password" placeholder="Your password" style="width: 100%; padding: 15px; font-size: 18px; border: 1px solid #ccc; border-radius: 4px; outline: none; height: 70px;">
            </div>
            <button type="submit">Login</button>
        </form>
    </div>
</body>
</html>

templates/userauths/sign-up.html
{% load static %}
<!DOCTYPE html>

<html lang="en" dir="ltr">
   <head>
      <meta charset="utf-8">
      <title>Login </title>
      <style>
        @import url("https://fonts.googleapis.com/css2?family=Open+Sans:wght@200;300;400;500;600;700&display=swap");
        * {
          margin: 0;
          padding: 0;
          box-sizing: border-box;
          font-family: "Open Sans", sans-serif;
        }
        body {
          display: flex;
          align-items: center;
          justify-content: center;
          min-height: 100vh;
          width: 100%;
          padding: 0 10px;
          color: #fff;
        }
        body::before {
          content: "";
          position: absolute;
          width: 100%;
          height: 100%;
          background-image: url('{% static 'assets/images/background1.jpeg' %}');
          background-position: center;
          background-size: cover;
        }
        .wrapper {
          width: 400px;
          border-radius: 8px;
          padding: 30px;
          text-align: center;
          border: 1px solid rgba(255, 255, 255, 0.5);
          backdrop-filter: blur(8px);
          -webkit-backdrop-filter: blur(8px);
        }
        .wrapper .title{
            font-size: 20px;
            font-weight: 600;
            text-align: center;
            line-height: 40px;
            color: brown;
            user-select: none;
            border-radius: 15px 15px 0 0;
            
          }
        form {
          display: flex;
          flex-direction: column;
        }
        .form-group {
         margin-bottom: 20px; /* Increased margin-bottom for more space */
     }
        .form-control {
            width: 100%;
            padding: 10px;
            font-size: 16px;
            border: 1px solid #ccc;
            border-radius: 4px;
            outline: none;
            height: 60px;
        }
        .form-control:focus {
            border-color: #007bff;
        }

        h2 {
          font-size: 2rem;
          margin-bottom: 20px;
          color: #fff;
        }
       
        
        button {
          background: #fff;
          color: #000;
          font-weight: 600;
          border: none;
          padding: 12px 20px;
          cursor: pointer;
          border-radius: 3px;
          font-size: 16px;
          border: 2px solid transparent;
          transition: 0.3s ease;
        }
        button:hover {
          color: #fff;
          border-color: #fff;
          background: rgba(255, 255, 255, 0.15);
        }
        .register {
          text-align: center;
          margin-top: 30px;
          color: #fff;
        }
      </style>
   </head>
   <body>
      <div class="wrapper">
         {% if form.errors %}
       <div class="alert alert danger ">
         <strong> {{form.errors}} </strong>
       </div>
         {% endif %}
         <div class="title">
            Create an Account
            <p>Already have an account? <a href="{% url 'userauths:sign-in' %}">login</a> </p>
         </div>
         <form method="post" method="POST">
            {% csrf_token %}
            <div class="form-group">
                {{form.username}}
            </div>
            <div class="form-group">
                {{form.email}}
            </div>
            <div class="form-group">
                {{form.password1}}
            </div>
            <div class="form-group">
                {{form.password2}}
            </div>

            <button type="submit">Register</button>
         </form>
            
        
         </form>
      </div>
   </body>
</html>